# Site Settings
title: ECO BLOG
email: dragontarget@naver.com
description: Some text about your blog.
baseurl: ""
url: "https://abcd1439.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: 김경제
user_description: 안녕하세요.
disqus_username: disqus_gPEM0qX0n4

# Social Media
# Remove the item if you don't need it
github_username: abcd1439


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
